# Generated by Django 3.1.7 on 2021-05-01 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('H', 'Hostel'), ('A', 'Academics'), ('M', 'Administrative'), ('N', 'none')], default='N', max_length=5)),
                ('Department', models.CharField(choices=[('CSE', 'Computer Engineering'), ('ECE', 'Electronics Engineering'), ('EE', 'Electrical Engineering'), ('CV', 'Civil Engineering'), ('IT', 'Information Technology'), ('N', 'None')], default='N', max_length=5)),
                ('details', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.student')),
            ],
        ),
    ]
