# Generated by Django 3.1.7 on 2021-05-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210501_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('S', 'Solved')], default='Pending', max_length=8, null=True),
        ),
    ]
