# Generated by Django 3.1.7 on 2021-05-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
