# Generated by Django 3.1.7 on 2021-05-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210503_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Department',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Information Technology', 'Information Technology'), ('N', 'None')], default='N', max_length=35),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='area',
            field=models.CharField(choices=[('Hostel', 'Hostel'), ('Academics', 'Academics'), ('Administrative', 'Administrative'), ('N', 'none')], default='N', max_length=25),
        ),
    ]
